CREATE TABLE `blog_posts` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`slug` text NOT NULL,
	`content` text NOT NULL,
	`excerpt` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`tags` text,
	`image_url` text,
	`image_alt` text,
	`author` text NOT NULL,
	`author_id` text NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`published_at` integer,
	FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `blog_posts_slug_unique` ON `blog_posts` (`slug`);--> statement-breakpoint
CREATE TABLE `certifications` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`issuer` text NOT NULL,
	`description` text NOT NULL,
	`category` text NOT NULL,
	`status` text DEFAULT 'active' NOT NULL,
	`skills` text NOT NULL,
	`issue_date` integer NOT NULL,
	`expiry_date` integer,
	`credential_id` text,
	`verification_url` text,
	`icon` text,
	`color` text,
	`display_order` integer DEFAULT 0 NOT NULL,
	`is_visible` integer DEFAULT true NOT NULL,
	`name_translations` text,
	`description_translations` text,
	`issuer_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `contact_inquiries` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`subject` text NOT NULL,
	`message` text NOT NULL,
	`status` text DEFAULT 'open' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer
);
--> statement-breakpoint
CREATE TABLE `education` (
	`id` text PRIMARY KEY NOT NULL,
	`institution` text NOT NULL,
	`degree` text NOT NULL,
	`degree_type` text NOT NULL,
	`field_of_study` text NOT NULL,
	`start_date` integer NOT NULL,
	`end_date` integer,
	`status` text DEFAULT 'completed' NOT NULL,
	`gpa` text,
	`achievements` text DEFAULT '[]' NOT NULL,
	`coursework` text DEFAULT '[]' NOT NULL,
	`projects` text DEFAULT '[]' NOT NULL,
	`extracurriculars` text DEFAULT '[]' NOT NULL,
	`location` text NOT NULL,
	`institution_url` text,
	`certificate_url` text,
	`transcript` text,
	`is_visible` integer DEFAULT true NOT NULL,
	`display_order` integer DEFAULT 0 NOT NULL,
	`institution_translations` text,
	`degree_translations` text,
	`field_of_study_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`subtitle` text NOT NULL,
	`description` text NOT NULL,
	`long_description` text,
	`technologies` text NOT NULL,
	`categories` text NOT NULL,
	`status` text DEFAULT 'completed' NOT NULL,
	`project_type` text NOT NULL,
	`start_date` integer NOT NULL,
	`end_date` integer,
	`github_url` text,
	`live_url` text,
	`demo_url` text,
	`documentation_url` text,
	`images` text DEFAULT '[]' NOT NULL,
	`key_features` text DEFAULT '[]' NOT NULL,
	`technical_challenges` text DEFAULT '[]' NOT NULL,
	`code_examples` text DEFAULT '[]' NOT NULL,
	`team_size` integer,
	`my_role` text,
	`client_name` text,
	`budget` text,
	`display_order` integer DEFAULT 0 NOT NULL,
	`is_visible` integer DEFAULT true NOT NULL,
	`is_featured` integer DEFAULT false NOT NULL,
	`is_open_source` integer DEFAULT false NOT NULL,
	`problem` text,
	`solution` text,
	`architecture` text,
	`title_translations` text,
	`description_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `services` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`category` text NOT NULL,
	`service_type` text NOT NULL,
	`description` text NOT NULL,
	`long_description` text,
	`features` text DEFAULT '[]' NOT NULL,
	`technologies` text DEFAULT '[]' NOT NULL,
	`duration` text,
	`complexity` text,
	`pricing_type` text NOT NULL,
	`base_price` text,
	`price_range` text,
	`deliverables` text DEFAULT '[]' NOT NULL,
	`requirements` text DEFAULT '[]' NOT NULL,
	`portfolio_examples` text DEFAULT '[]' NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`is_popular` integer DEFAULT false NOT NULL,
	`display_order` integer DEFAULT 0 NOT NULL,
	`name_translations` text,
	`description_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `skills` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`category` text NOT NULL,
	`sub_category` text,
	`proficiency_level` integer NOT NULL,
	`proficiency_label` text NOT NULL,
	`years_of_experience` integer NOT NULL,
	`description` text,
	`icon` text,
	`color` text,
	`related_skills` text DEFAULT '[]' NOT NULL,
	`certifications` text DEFAULT '[]' NOT NULL,
	`projects` text DEFAULT '[]' NOT NULL,
	`last_used` integer NOT NULL,
	`is_visible` integer DEFAULT true NOT NULL,
	`display_order` integer DEFAULT 0 NOT NULL,
	`name_translations` text,
	`description_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `testimonials` (
	`id` text PRIMARY KEY NOT NULL,
	`quote` text NOT NULL,
	`author` text NOT NULL,
	`role` text NOT NULL,
	`company` text NOT NULL,
	`author_image` text,
	`author_linkedin` text,
	`company_url` text,
	`company_logo` text,
	`rating` integer,
	`is_verified` integer DEFAULT false NOT NULL,
	`verification_date` integer,
	`display_order` integer DEFAULT 0 NOT NULL,
	`is_visible` integer DEFAULT true NOT NULL,
	`is_featured` integer DEFAULT false NOT NULL,
	`quote_translations` text,
	`author_translations` text,
	`role_translations` text,
	`company_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text NOT NULL,
	`password` text NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`role` text DEFAULT 'visitor' NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`last_login` integer,
	`access_token` text,
	`refresh_token` text,
	`session_id` text,
	`avatar` text,
	`bio` text,
	`location` text,
	`website` text,
	`linkedin` text,
	`twitter` text,
	`github` text,
	`facebook` text,
	`instagram` text,
	`youtube` text,
	`tiktok` text,
	`pinterest` text,
	`reddit` text,
	`telegram` text,
	`whatsapp` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);--> statement-breakpoint
CREATE TABLE `work_experiences` (
	`id` text PRIMARY KEY NOT NULL,
	`role` text NOT NULL,
	`company` text NOT NULL,
	`location` text NOT NULL,
	`start_date` integer NOT NULL,
	`end_date` integer,
	`description` text NOT NULL,
	`achievements` text NOT NULL,
	`technologies` text NOT NULL,
	`responsibilities` text NOT NULL,
	`employment_type` text NOT NULL,
	`industry` text NOT NULL,
	`company_url` text,
	`logo` text,
	`display_order` integer DEFAULT 0 NOT NULL,
	`is_visible` integer DEFAULT true NOT NULL,
	`is_featured` integer DEFAULT false NOT NULL,
	`role_translations` text,
	`company_translations` text,
	`description_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
