CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"role" text DEFAULT 'visitor' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone,
	"last_login" timestamp with time zone,
	"access_token" text,
	"refresh_token" text,
	"session_id" text,
	"avatar" text,
	"bio" text,
	"location" text,
	"website" text,
	"linkedin" text,
	"twitter" text,
	"github" text,
	"facebook" text,
	"instagram" text,
	"youtube" text,
	"tiktok" text,
	"pinterest" text,
	"reddit" text,
	"telegram" text,
	"whatsapp" text,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
