CREATE TABLE `projects` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`subtitle` text NOT NULL,
	`description` text NOT NULL,
	`long_description` text,
	`technologies` text NOT NULL,
	`categories` text NOT NULL,
	`status` text DEFAULT 'completed' NOT NULL,
	`project_type` text NOT NULL,
	`start_date` integer NOT NULL,
	`end_date` integer,
	`github_url` text,
	`live_url` text,
	`demo_url` text,
	`documentation_url` text,
	`images` text DEFAULT '[]' NOT NULL,
	`key_features` text NOT NULL,
	`technical_challenges` text DEFAULT '[]' NOT NULL,
	`code_examples` text DEFAULT '[]' NOT NULL,
	`team_size` integer,
	`my_role` text,
	`client_name` text,
	`budget` text,
	`display_order` integer DEFAULT 0 NOT NULL,
	`is_visible` integer DEFAULT true NOT NULL,
	`is_featured` integer DEFAULT false NOT NULL,
	`is_open_source` integer DEFAULT false NOT NULL,
	`title_translations` text,
	`description_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `skills` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`category` text NOT NULL,
	`sub_category` text,
	`proficiency_level` integer NOT NULL,
	`proficiency_label` text NOT NULL,
	`years_of_experience` integer NOT NULL,
	`description` text,
	`icon` text,
	`color` text,
	`related_skills` text DEFAULT '[]' NOT NULL,
	`certifications` text DEFAULT '[]' NOT NULL,
	`projects` text DEFAULT '[]' NOT NULL,
	`last_used` integer NOT NULL,
	`is_visible` integer DEFAULT true NOT NULL,
	`display_order` integer DEFAULT 0 NOT NULL,
	`name_translations` text,
	`description_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `work_experiences` (
	`id` text PRIMARY KEY NOT NULL,
	`role` text NOT NULL,
	`company` text NOT NULL,
	`location` text NOT NULL,
	`start_date` integer NOT NULL,
	`end_date` integer,
	`description` text NOT NULL,
	`achievements` text NOT NULL,
	`technologies` text NOT NULL,
	`responsibilities` text NOT NULL,
	`employment_type` text NOT NULL,
	`industry` text NOT NULL,
	`company_url` text,
	`logo` text,
	`display_order` integer DEFAULT 0 NOT NULL,
	`is_visible` integer DEFAULT true NOT NULL,
	`is_featured` integer DEFAULT false NOT NULL,
	`role_translations` text,
	`company_translations` text,
	`description_translations` text,
	`created_at` integer NOT NULL,
	`updated_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
