import {
  SECTION_IDS,
  FORM_IDS,
  ANIMATION_DURATIONS,
  ANIMATION_DELAYS,
} from "#/lib";

export const CONTACT_CONSTANTS = {
  SECTION_ID: SECTION_IDS.CONTACT,
  FORM_ID: FORM_IDS.CONTACT_FORM,
  FORM_NAME_ID: FORM_IDS.CONTACT_NAME,
  FORM_EMAIL_ID: FORM_IDS.CONTACT_EMAIL,
  FORM_MESSAGE_ID: FORM_IDS.CONTACT_MESSAGE,
  FORM_BUTTON_ID: FORM_IDS.CONTACT_BUTTON,
  ANIMATION: {
    TITLE_DURATION: ANIMATION_DURATIONS.SLOW,
    FORM_DURATION: ANIMATION_DURATIONS.MEDIUM,
    FORM_DELAY: ANIMATION_DELAYS.LARGE,
  },
} as const;
