import { SECTION_IDS, ANIMATION_DURATIONS, ANIMATION_DELAYS } from "#/lib";

export const ABOUT_CONSTANTS = {
  SECTION_ID: SECTION_IDS.ABOUT,
  ANIMATION: {
    TITLE_DURATION: ANIMATION_DURATIONS.MEDIUM,
    SKILLS_DURATION: ANIMATION_DURATIONS.MEDIUM,
    SKILLS_DELAY: ANIMATION_DELAYS.MEDIUM,
    DESCRIPTION_DURATION: ANIMATION_DURATIONS.MEDIUM,
    DESCRIPTION_DELAY: ANIMATION_DELAYS.LARGE,
  },
  SKILLS: {
    CODE_CONJURER: "codeConjurer",
    BRAND_ARCHITECT: "brandArchitect",
    DESIGN_DREAMER: "designDreamer",
    PROBLEM_SOLVER: "problemSolver",
    TEAM_PLAYER: "teamPlayer",
    INNOVATION_ARCHITECT: "innovationArchitect",
    DIGITAL_STORYTELLER: "digitalStoryteller",
  },
} as const;
